name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flask flask_sqlalchemy flask_restful

    - name: Run Pylint on changed files only
      run: |
        # Get the initial commit hash (the very first commit in the repository)
        initial_commit=$(git rev-list --max-parents=0 HEAD)

        # Check if the current commit is the initial commit
        if [ "$(git rev-parse HEAD)" = "$initial_commit" ]; then
          # If it's the initial commit, run Pylint on all Python files
          echo "Initial commit detected. Running Pylint on all Python files."
          pylint --disable=C0304 $(git ls-files '*.py')  # Disable C0304 (final newline missing) warning
        else
          # If it's not the initial commit, get a list of changed Python files in the latest commit
          changed_files=$(git diff --name-only HEAD^ HEAD -- '*.py')
          
          # Check if there are any changed Python files
          if [ -n "$changed_files" ]; then
            echo "Running Pylint on changed files:"
            echo "$changed_files"  # Print the list of changed files for clarity
            pylint --disable=C0304 $changed_files  # Disable C0304 (final newline missing) warning
          else
            echo "No Python files changed. Skipping Pylint."  # Skip if no Python files were changed
          fi
        fi
